---
abstract: 'A tiny script to install dependent modules'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-installdeps
requires:
  Getopt::Config::FromPod: 0
  Module::ExtractUse: 0.30
  perl: 5.006
  version: 0.77
resources:
  homepage: https://github.com/yak1ex/App-installdeps
  repository: https://github.com/yak1ex/App-installdeps.git
version: v0.0.3
